import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='flex justify-between'>
          <Link href="./">RAWRISANG ART</Link>
          <div className='menu'>
            <ul>
              <li><Link href="./">ARTWORKS</Link></li>
              <li><Link href="./">ABOUT</Link></li>
              <li><Link href="./">CONTACT</Link></li>
            </ul>
          </div>
        </header>
        {children}
        </body>
        <footer className='flex justify-between items-center'>
          <div>
            <h3>JOIN MY NEWSLETTER</h3>
            <form action="">
              <input type="text" placeholder='Your Email Address' />
              <button type='submit'>SIGN UP</button>
            </form>
          </div>
          <div>
            <h3>SOCIALS</h3>
            <ul>
              <li><Link href="./">Instagram</Link></li>
              <li><Link href="./">TikTok</Link></li> 
              <li><Link href="./">LinkedIn</Link></li>
            </ul>
          </div>
        </footer>
    </html>
  )
}
